### ISSUE TITLE
A Problem With Fastuniq

### ISSUE THREAD

**Issue by Ataliai** [hadasvolk/CompLabNGS#14]
According to the files I received in the project (GSE229677) I should run fastuniq for PE. Each such file is huge (11 GB) and it seems that I don't have enough RAM on my computer for this purpose (there is a log of out of memory). Is there another alternative?

**Comment by hadasvolk** [comment]
Why would you want to run fastuniq? what is the biological experiment you are analyzing and what will you benefit from deduplication?

**Comment by tehilayehudai** [comment]
Hi, I join the question.  We thought a duplicate should be removed based on this slide in presentation 8.

![IMG-20240516-WA0053](https://github.com/hadasvolk/CompLabNGS/assets/59171638/7264ad9a-14d6-46fa-8192-91b729bd1643)

**Comment by hadasvolk** [comment]
Ok, I understand. It is a valid confusion probably caused by me; I'll make sure to remove it in future courses.

What I tried to say is that deduplication can be used in RNA Seq if there is a sufficient QC information that encourage us to do it. In RNA Seq we ultimately aim to quantify the expression profiles of transcripts, as such we expect some level of duplication in the data. If our QC returns huge duplication values then we should consider deduplicate it. On the data you downloaded there is no need to do that

**Comment by tehilayehudai** [comment]
I understand.. We will repet the analysis again, because we have already removed the duplicates.
Thanks for the quick reply!!

**Comment by KerenRozen** [comment]
Is it possible to continue the analysis with the data after using fastuniq?

**Comment by hadasvolk** [comment]
It is possible, but you need to explain the rational behind doing so. What part of the data or understanding of the biological context of the experiment set you on this rational?!

**Comment by KerenRozen** [comment]
OK. Thanks for your answer
